### ISSUE TITLE
Retrospectives History: expand retrospective throws error in application

### ISSUE THREAD

**Issue by kw80** [microsoft/vsts-extension-retrospectives#457]
Using latest Restrospectives extension 1.80.13

Go to Boards > Retrospectives > Tab History
![1](https://user-images.githubusercontent.com/58734395/192280187-e9954efd-dd63-4eb7-b5d9-1286a77b2541.PNG)
Expand retrospective with a few work items = OK
Expand retrospective with +50 work items = ERROR
![2](https://user-images.githubusercontent.com/58734395/192280202-53431f09-7258-4ebd-bfd0-8ae30717e500.PNG)

Network logging in web developer tools shows the number of items including is cut off at 29 whereas it's +50 items:
POST https://dc.services.visualstudio.com/v2/track
Payload
[
{time: "2022-09-26T12:36:57.148Z", iKey: "128***148",…},…]
0: {time: "2022-09-26T12:36:57.148Z", iKey: "128***148",…}
1: {time: "2022-09-26T12:36:57.160Z", iKey: "128***148",…}

Preview:
appId: "379***6d5"
errors: []
itemsAccepted: 29
itemsReceived: 29

When expanding a smaller retrospective with a few work items, you do not hit this limit:
{itemsReceived: 15, itemsAccepted: 15, errors: [], appId: "379***6d5"}
appId: "379***6d5"
errors: []
itemsAccepted: 15
itemsReceived: 15

Tested using multiple browsers (Edge, Chrome) + cleared all history data from the browser first.
All users experience this behaviour on separate workstations.

Further network logging:
console.error: TypeError: Cannot read properties of undefined (reading 'displayName')","hasFullStack":true,"stack":"TypeError: Cannot read properties of undefined (reading 'displayName') at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.80.13/166***768/dist/reflect-bundle.js:2:1390028 at Array.forEach (<anonymous>) at o.buildActionItemsList (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-retrospectives/1.80.13/166***768/dist/reflect-bundle.js:2:1389754

**Comment by mindlessroman** [comment]
Great catch! Thank you for the find and for the details.
