### ISSUE TITLE
AzDo retrospective boards

### ISSUE THREAD

**Issue by skitch21** [microsoft/vsts-extension-retrospectives#468]
Hi,
 
I’m struggling to get to the retrospective boards today.  I just get the error message “We detected an error in the application”.  This started happening after I had been creating some new column names and deleting old column names from a particular retro board.  
Is there a way to reset the board back to a default setting before the changes were made or another work around?

![Retrospective board](https://user-images.githubusercontent.com/36794341/196966785-c63885cc-0127-46f8-b611-d185ff54e43c.png)

**Comment by AMACStogowski** [comment]
I am experiencing this exact issue as well. The board was working well until I deleted a column. Seems like the same cause as the OP.

Any advice or workarounds would be appreciated.

**Comment by mindlessroman** [comment]
Hey folks (@AMACStogowski, @skitch21 ) - I've tried to recreate this on my end but haven't found the culprit behavior yet. Would either of your being able go through this process with the developer tools console open? Having the exact error would be helpful in tracking down what caused this.

**Comment by AMACStogowski** [comment]
@mindlessroman - My team can certainly work with you on this. Let me know how we can connect.

**Comment by dkritsky** [comment]
Here's the error.

```
reflect-bundle.js:2 TypeError: Cannot read properties of undefined (reading 'columnProperties')
    at t.render (reflect-bundle.js:2:1539143)
    at qa (reflect-bundle.js:2:1190631)
    at Va (reflect-bundle.js:2:1190430)
    at qs (reflect-bundle.js:2:1231189)
    at Sl (reflect-bundle.js:2:1217407)
    at xl (reflect-bundle.js:2:1217335)
    at wl (reflect-bundle.js:2:1217198)
    at gl (reflect-bundle.js:2:1214185)
    at reflect-bundle.js:2:1164006
    at t.unstable_runWithPriority (reflect-bundle.js:2:1364128) []
```

**Comment by Juanflu** [comment]
Hi! In my case I got to this point after sending a POST request to the API, like this:

`POST: https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/98b9e409-ed7f-4088-ac84-95e2f88cc166/Documents?api-version=3.1-preview.1`

This created a new retrospective with the wrong structure, lacking of the rest of properties:

```json
{
    "id": "53855c65-a243-4834-8fa1-7e21125841f0",
    "__etag": 1
}
```

Is there a way to delete this retro from the API? I'm pretty sure this would solve the issue.

**Comment by Juanflu** [comment]
> Hi! In my case I got to this point after sending a POST request to the API, like this:
> 
> `POST: https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/98b9e409-ed7f-4088-ac84-95e2f88cc166/Documents?api-version=3.1-preview.1`
> 
> This created a new retrospective with the wrong structure, lacking of the rest of properties:
> 
> ```json
> {
>     "id": "53855c65-a243-4834-8fa1-7e21125841f0",
>     "__etag": 1
> }
> ```
> 
> Is there a way to delete this retro from the API? I'm pretty sure this would solve the issue.

Ok, I got to delete it, just send a `DELETE` request like this:

`DELETE https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/98b9e409-ed7f-4088-ac84-95e2f88cc166/Documents/{retrospective_id}?api-version=3.1-preview.1`

**Comment by AMACStogowski** [comment]
> 

This helped and we were able to delete the bad retro in question - thank you!

**Comment by DiederickA** [comment]
> > Hi! In my case I got to this point after sending a POST request to the API, like this:
> > `POST: https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/{collection_id}/Documents?api-version=3.1-preview.1`
> > This created a new retrospective with the wrong structure, lacking of the rest of properties:
> > ```json
> > {
> >     "id": "53855c65-a243-4834-8fa1-7e21125841f0",
> >     "__etag": 1
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a way to delete this retro from the API? I'm pretty sure this would solve the issue.
> 
> Ok, I got to delete it, just send a `DELETE` request like this:
> 
> `DELETE https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/{collection_id}/Documents/{retrospective_id}?api-version=3.1-preview.1`
> 
> For those who need more info, you can retrieve all the retrospectives in the collection through a GET request:
> 
> `GET https://extmgmt.dev.azure.com/{organization}/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-retrospectives/Data/Scopes/Default/Current/Collections/{collection_id}/Documents?api-version=3.1-preview.1`
> 
> Then, you can check the object structure of your retros. In my case it would be something like this:
> 
> ```json
...
> 
> I hope it helps!

What would be the {collection_id} in the URL?
